#!/bin/sh

#  original
#  ((sleep 2 && cd /www/software10/html/jikes && cvs update -Pd > /tmp/jikes.last.www.commit 2>&1) &)

sleep 2
FILE=/tmp/jikes.last.www.commit.$$
cd /www/software10/html/jikes
date > $FILE
hostname >> $FILE
cvs update -dAP >> $FILE 2>&1
mail -s "CVS UPDATE" jikes@cabbey.net < $FILE
rm $FILE
