// $Id$
// DO NOT MODIFY THIS FILE - it is generated using jikespg on java.g.
//
// This software is subject to the terms of the IBM Jikes Compiler Open
// Source License Agreement available at the following URL:
// http://ibm.com/developerworks/opensource/jikes.
// Copyright (C) 1996, 2003 IBM Corporation and others.  All Rights Reserved.
// You must accept the terms of that agreement to use this software.
//

#ifndef javasym_INCLUDED
#define javasym_INCLUDED

#ifdef HAVE_JIKES_NAMESPACE
namespace Jikes { // Open namespace Jikes block
#endif

enum {
      TK_abstract = 37,
      TK_assert = 65,
      TK_boolean = 5,
      TK_break = 66,
      TK_byte = 6,
      TK_case = 99,
      TK_catch = 100,
      TK_char = 7,
      TK_class = 55,
      TK_continue = 67,
      TK_default = 101,
      TK_do = 68,
      TK_double = 8,
      TK_else = 95,
      TK_extends = 102,
      TK_false = 22,
      TK_final = 38,
      TK_finally = 103,
      TK_float = 9,
      TK_for = 69,
      TK_if = 70,
      TK_implements = 104,
      TK_import = 81,
      TK_instanceof = 56,
      TK_int = 10,
      TK_interface = 96,
      TK_long = 11,
      TK_native = 39,
      TK_new = 13,
      TK_null = 23,
      TK_package = 105,
      TK_private = 40,
      TK_protected = 41,
      TK_public = 42,
      TK_return = 71,
      TK_short = 12,
      TK_static = 36,
      TK_strictfp = 43,
      TK_super = 16,
      TK_switch = 72,
      TK_synchronized = 35,
      TK_this = 17,
      TK_throw = 73,
      TK_throws = 106,
      TK_transient = 44,
      TK_true = 24,
      TK_try = 74,
      TK_void = 18,
      TK_volatile = 45,
      TK_while = 63,
      TK_Identifier = 2,
      TK_IntegerLiteral = 25,
      TK_LongLiteral = 26,
      TK_FloatLiteral = 27,
      TK_DoubleLiteral = 28,
      TK_CharacterLiteral = 29,
      TK_StringLiteral = 30,
      TK_PLUS_PLUS = 14,
      TK_MINUS_MINUS = 15,
      TK_EQUAL_EQUAL = 75,
      TK_LESS_EQUAL = 57,
      TK_GREATER_EQUAL = 58,
      TK_NOT_EQUAL = 76,
      TK_LEFT_SHIFT = 47,
      TK_RIGHT_SHIFT = 48,
      TK_UNSIGNED_RIGHT_SHIFT = 49,
      TK_PLUS_EQUAL = 82,
      TK_MINUS_EQUAL = 83,
      TK_MULTIPLY_EQUAL = 84,
      TK_DIVIDE_EQUAL = 85,
      TK_AND_EQUAL = 86,
      TK_OR_EQUAL = 87,
      TK_XOR_EQUAL = 88,
      TK_REMAINDER_EQUAL = 89,
      TK_LEFT_SHIFT_EQUAL = 90,
      TK_RIGHT_SHIFT_EQUAL = 91,
      TK_UNSIGNED_RIGHT_SHIFT_EQUAL = 92,
      TK_OR_OR = 97,
      TK_AND_AND = 77,
      TK_PLUS = 19,
      TK_MINUS = 20,
      TK_NOT = 50,
      TK_REMAINDER = 59,
      TK_XOR = 78,
      TK_AND = 79,
      TK_MULTIPLY = 54,
      TK_OR = 80,
      TK_TWIDDLE = 51,
      TK_DIVIDE = 60,
      TK_GREATER = 61,
      TK_LESS = 62,
      TK_LPAREN = 1,
      TK_RPAREN = 4,
      TK_LBRACE = 32,
      TK_RBRACE = 46,
      TK_LBRACKET = 31,
      TK_RBRACKET = 64,
      TK_SEMICOLON = 3,
      TK_QUESTION = 98,
      TK_COLON = 52,
      TK_COMMA = 34,
      TK_DOT = 21,
      TK_EQUAL = 53,
      TK_BodyMarker = 107,
      TK_enum = 108,
      TK_AT = 33,
      TK_ELLIPSIS = 94,
      TK_const = 109,
      TK_goto = 110,
      TK_ERROR = 111,
      TK_EOF = 93
     };

#ifdef HAVE_JIKES_NAMESPACE
} // Close namespace Jikes block
#endif

#endif /* javasym_INCLUDED */
