// $Id$
// DO NOT MODIFY THIS FILE - it is generated using jikespg on java.g.
//
// This software is subject to the terms of the IBM Jikes Compiler Open
// Source License Agreement available at the following URL:
// http://ibm.com/developerworks/opensource/jikes.
// Copyright (C) 1996, 2003 IBM Corporation and others.  All Rights Reserved.
// You must accept the terms of that agreement to use this software.
//

#ifndef javasym_INCLUDED
#define javasym_INCLUDED

#ifdef HAVE_JIKES_NAMESPACE
namespace Jikes { // Open namespace Jikes block
#endif

enum {
      TK_abstract = 41,
      TK_assert = 72,
      TK_boolean = 5,
      TK_break = 73,
      TK_byte = 6,
      TK_case = 99,
      TK_catch = 100,
      TK_char = 7,
      TK_class = 56,
      TK_continue = 74,
      TK_default = 101,
      TK_do = 75,
      TK_double = 8,
      TK_else = 98,
      TK_extends = 76,
      TK_false = 24,
      TK_final = 42,
      TK_finally = 102,
      TK_float = 9,
      TK_for = 77,
      TK_if = 78,
      TK_implements = 104,
      TK_import = 83,
      TK_instanceof = 57,
      TK_int = 10,
      TK_interface = 96,
      TK_long = 11,
      TK_native = 43,
      TK_new = 18,
      TK_null = 25,
      TK_package = 105,
      TK_private = 44,
      TK_protected = 45,
      TK_public = 46,
      TK_return = 79,
      TK_short = 12,
      TK_static = 40,
      TK_strictfp = 47,
      TK_super = 13,
      TK_switch = 80,
      TK_synchronized = 39,
      TK_this = 20,
      TK_throw = 81,
      TK_throws = 106,
      TK_transient = 48,
      TK_true = 26,
      TK_try = 82,
      TK_void = 21,
      TK_volatile = 49,
      TK_while = 65,
      TK_Identifier = 2,
      TK_IntegerLiteral = 27,
      TK_LongLiteral = 28,
      TK_FloatLiteral = 29,
      TK_DoubleLiteral = 30,
      TK_CharacterLiteral = 31,
      TK_StringLiteral = 32,
      TK_PLUS_PLUS = 15,
      TK_MINUS_MINUS = 16,
      TK_EQUAL_EQUAL = 66,
      TK_LESS_EQUAL = 58,
      TK_GREATER_EQUAL = 59,
      TK_NOT_EQUAL = 67,
      TK_LEFT_SHIFT = 51,
      TK_RIGHT_SHIFT = 33,
      TK_UNSIGNED_RIGHT_SHIFT = 38,
      TK_PLUS_EQUAL = 84,
      TK_MINUS_EQUAL = 85,
      TK_MULTIPLY_EQUAL = 86,
      TK_DIVIDE_EQUAL = 87,
      TK_AND_EQUAL = 88,
      TK_OR_EQUAL = 89,
      TK_XOR_EQUAL = 90,
      TK_REMAINDER_EQUAL = 91,
      TK_LEFT_SHIFT_EQUAL = 92,
      TK_RIGHT_SHIFT_EQUAL = 93,
      TK_UNSIGNED_RIGHT_SHIFT_EQUAL = 94,
      TK_OR_OR = 97,
      TK_AND_AND = 68,
      TK_PLUS = 22,
      TK_MINUS = 23,
      TK_NOT = 52,
      TK_REMAINDER = 60,
      TK_XOR = 69,
      TK_AND = 63,
      TK_MULTIPLY = 54,
      TK_OR = 70,
      TK_TWIDDLE = 53,
      TK_DIVIDE = 61,
      TK_GREATER = 19,
      TK_LESS = 34,
      TK_LPAREN = 1,
      TK_RPAREN = 3,
      TK_LBRACE = 36,
      TK_RBRACE = 50,
      TK_LBRACKET = 14,
      TK_RBRACKET = 71,
      TK_SEMICOLON = 4,
      TK_QUESTION = 64,
      TK_COLON = 55,
      TK_COMMA = 35,
      TK_DOT = 17,
      TK_EQUAL = 62,
      TK_BodyMarker = 107,
      TK_enum = 108,
      TK_AT = 37,
      TK_ELLIPSIS = 103,
      TK_const = 109,
      TK_goto = 110,
      TK_ERROR = 111,
      TK_EOF = 95
     };

#ifdef HAVE_JIKES_NAMESPACE
} // Close namespace Jikes block
#endif

#endif /* javasym_INCLUDED */
